name: Cloud Function CI
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_CREDENTIALS }}'
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@v1
        name: 'Deploy API to Google Cloud'
        with:
          name: bernachon-api
          runtime: python37
          entry_point: entry_point
          region: europe-west6
          source_dir: api
          env_vars: AgraffeService=Google Cloud Functions,OPENWEATHERMAP_API_KEY=${{ secrets.OPENWEATHERMAP_API_KEY }},COORDS_LAT=${{ secrets.COORDS_LAT }},COORDS_LON=${{ secrets.COORDS_LON }}
